-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2015 Statoil
 
MULTFLT        --         changed by Phoo
  'E_01'       0/         --0.01  /
  'E_01_F3'    0/         --0.01  /
  'DE_1'       0/         --3.9  /
  'DE_1_LTo'   0/         --0.01 /
  'DE_B3'      0/         --0.00075 / 
  'DE_2'       0/         --0.015  /
  'DE_0'       0/         --20  /
  'BC'         0/         --0.1 /   
  'CD'         0/         --0.1 /
  'CD_To'      0/         --0.01 /
  'CD_B3'      0/         --0.1 /
  'CD_0'       0/         --1 /  
  'CD_1'       0/         --0.1 /
  'C_01'       0/         --0.01 /
  'C_01_Ti'    0/         --0.01 /
  'C_08'       0/         --0.01 /
  'C_08_Ile'   0/         --0.1 /
  'C_08_S'     0/         --0.01 /
  'C_08_Ti'    0/         --1 /
  'C_08_S_Ti'  0/         --1 /
  'C_09'       0/         --0.1 /    
  'C_02'       0/         --0.01 /
  'C_04'       0/         --0.05 /
  'C_05'       0/         --0.1 /
  'C_06'       0/         --0.1 /
  'C_10'       0/         --0.01 /
  'C_12'       0/         --0.1 /
  'C_20'       0/         --0.5 / 
  'C_20_LTo'   0/         --0.5 /
  'C_21'       0/         --0.001 /
  'C_21_Ti'    0/         --0.001 /
  'C_22'       0/         --0.001 /
  'C_23'       0/         --0.1 /
  'C_24'       0/         --0.1 /
  'C_25'       0/         --0.1 /
  'C_26'       0/         --0.1 /
  'C_26N'      0/         --0.001 /
  'C_27'       0/         --0.05 /
  'C_28'       0/         --1.0 /
  'C_29'       0/         --0.1 /  
  'DI'         0/         --0.1 /
  'DI_S'       0/         --0.1 /
  'D_05'       0/         --0.01 /
  'EF'         0/         --1.0 /
  'GH'         0/         --1.0 /
  'G_01'       0/         --0.05  / matand 0.05
  'G_02'       0/         --0.05 /
  'G_03'       0/         --1 / matand 0.05
  'G_05'       0/         --0.5 /
  'G_07'       0/         --0.05 / matand 0.05
  'G_08'       0/         --0.05 /
  'G_09'       0/         --0.05 /
  'G_13'       0/         --0.05 /
  'H_03'       0/         --1.0 /
  'IH'         0/         --1.0 /
  'm_east'     0/         --1.0 /
  'm_east_2'   0/         --1.0 /
  'm_north'    0/         --1.0 /
  'm_northe'   0/         --1.0 /
  'm_west'     0/         --1.0 /
/
