-- REGIONS

EQUALS
--            I1  I2  J1  J2  K1  K2
FIPNUM   1    1*  1*  1*  1*  1  17 / 
FIPNUM   2    1*  1*  1*  1*  18  22 / 

EQLNUM   1    1*  1*  1*  1*  1  17 / 
EQLNUM   2    1*  1*  1*  1*  18  22 /

SATNUM   1    1*  1*  1*  1*  1  17 / 
SATNUM   2    1*  1*  1*  1*  18  22 /

PVTNUM   1    1*  1*  1*  1*  1  17 / 
PVTNUM   2    1*  1*  1*  1*  18  22 /

ENDNUM   1    1*  1*  1*  1*  1  17 / 
ENDNUM   2    1*  1*  1*  1*  18  22 /


/